### ISSUE TITLE
When to publish to pub.dev?

### ISSUE THREAD

**Issue by jimmyhuang1992** [SchabanBo/q_overlay#3]
Hi :)

Have any exactly time to publish ? thank you very much!

**Comment by SchabanBo** [comment]
Hi @yingming25,
I am currently working on that. I will try to finish this until next month.

**Comment by jimmyhuang1992** [comment]
@SchabanBo Thanks 😄

**Comment by SchabanBo** [comment]
@yingming25 You can find the package [here](https://pub.dev/packages/overlayment)
